name: Clone repo

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone other repository
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://github.com/kerzendorf-group/kerzendorf-group.github.io.git
          git clone https://github.com/kerzendorf-group/group-data.git

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Clone my-other-repo"
          git push
