name: Clone repo

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone kerzendorf-group.github.io
        run: git clone git@github.com:kerzendorf-group/kerzendorf-group.github.io.git

      - name: Clone group-data
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@github.com:kerzendorf-group/group-data.git

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Clone my-other-repo"
          git push
