name: Clone repo

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: List items
        run: |
          cd group-data
          ls -a

      - name: Clone kerzendorf-group.github.io
        run: git clone https://${{ secrets.ACCESS_DATA }}@github.com/kerzendorf-group/kerzendorf-group.github.io.git

      - name: Clone group-data
        run: |
          git clone https://${{ secrets.ACCESS_DATA }}@github.com/kerzendorf-group/group-data.git

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Clone my-other-repo"
          git push

      - name: List items
        run: |
          cd kerzendorf-group.github.io
          ls -a
          cd ../group-web
          ls -a
